spring:
    main:
        banner-mode: "off"
    profiles:
        active: ${PROFILE:dev}
    application:
        name: "@project.name@"
        version: "@project.version@"
        description: "@project.description@"
        groupId: "@project.groupId@"
        artifactId: "@project.artifactId@"
        java: "@java.version@"
    mvc:
      pathmatch:
        matching-strategy: ant-path-matcher
logging:
  level:
     root: "off"
server:
    port: 8500
    servlet:
        context-path: "/@project.artifactId@"
      
